import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
SLACK_WEBHOOK = os.getenv("SLACK_WEBHOOK")
OPENOBSERVE_URL = os.getenv("OPENOBSERVE_URL")
OPENOBSERVE_TOKEN = os.getenv("OPENOBSERVE_TOKEN")
